const questions = [
  {
    id: 1,
    question: "What is the result of 5 + 3?",
    options: [7, 8, 6, 9],
    answer: 8,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 2,
    question: "How many fingers do you have on one hand?",
    options: [10, 5, 8, 6],
    answer: 5,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 3,
    question:
      "If a square has a side length of 4 units, what is its perimeter?",
    options: [12, 16, 8, 20],
    answer: 16,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 4,
    question: "What is the value of π (pi) to two decimal places?",
    options: [3.14, 3.25, 3.05, 3.2],
    answer: 3.14,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 5,
    question: "If x = 10 and y = 5, what is the value of x - y?",
    options: [15, 10, 5, 20],
    answer: 5,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 6,
    question: "What is the sum of the first 10 positive integers?",
    options: [45, 55, 50, 60],
    answer: 55,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 7,
    question:
      "If a triangle has angles measuring 30°, 60°, and 90°, what type of triangle is it?",
    options: ["Equilateral", "Isosceles", "Scalene", "Right-angled"],
    answer: "Right-angled",
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 8,
    question: "What is the product of 7 and 9?",
    options: [56, 63, 72, 81],
    answer: 63,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 9,
    question:
      "If a rectangle has length 8 units and width 5 units, what is its area?",
    options: [40, 13, 26, 20],
    answer: 40,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 10,
    question: "What is the next prime number after 17?",
    options: [19, 21, 23, 25],
    answer: 19,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 11,
    question:
      "If a car travels at a speed of 60 miles per hour, how far will it travel in 3 hours?",
    options: [150, 180, 120, 200],
    answer: 180,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 12,
    question: "Simplify: 2 × (4 + 6) - 3",
    options: [19, 17, 13, 15],
    answer: 17,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 13,
    question: "What is the square of 5?",
    options: [20, 25, 30, 35],
    answer: 25,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 14,
    question:
      "If a box contains 12 chocolates and you take 3, how many chocolates are left?",
    options: [6, 7, 9, 8],
    answer: 9,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 15,
    question:
      "What is the perimeter of a square with a side length of 6 units?",
    options: [18, 24, 12, 30],
    answer: 24,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 16,
    question:
      "If the sum of two numbers is 15 and one number is 8, what is the other number?",
    options: [6, 7, 9, 10],
    answer: 7,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 17,
    question: "What is the result of 4 × 5 ÷ 2?",
    options: [10, 12, 8, 14],
    answer: 10,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 18,
    question:
      "If a clock shows 3:45, how many degrees is the angle between the hour and minute hands?",
    options: [112.5, 120, 135, 150],
    answer: 112.5,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 19,
    question: "What is the value of 3 squared?",
    options: [6, 9, 12, 15],
    answer: 9,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 20,
    question:
      "If a shirt costs $20 and is on sale for 15% off, what is the sale price?",
    options: [17, 18, 19, 21],
    answer: 17,
    topic: "Maths",
    lvl: "easy",
  },
  {
    id: 21,
    question: "Solve for x: 2x + 5 = 15",
    options: [5, 6, 7, 8],
    answer: 5,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 22,
    question:
      "If a train travels at a speed of 40 meters per second, how far will it travel in 8 seconds?",
    options: [240, 280, 320, 360],
    answer: 320,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 23,
    question:
      "The average of three numbers is 15. If two of the numbers are 10 and 20, what is the third number?",
    options: [5, 15, 25, 30],
    answer: 25,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 24,
    question:
      "If a rectangle has a perimeter of 30 units and one side length is 8 units, what is the length of the other side?",
    options: [7, 6, 5, 9],
    answer: 7,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 25,
    question: "Simplify: (3 + 4) × 2 - 5",
    options: [12, 15, 18, 20],
    answer: 15,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 26,
    question:
      "The area of a triangle is 48 square units, and its base is 12 units. What is the height of the triangle?",
    options: [4, 6, 8, 10],
    answer: 8,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 27,
    question:
      "If the radius of a circle is 5 units, what is the circumference of the circle? (Use π = 3.14)",
    options: [15.7, 18.8, 21, 31.4],
    answer: 31.4,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 28,
    question: "What is the sum of the interior angles of a hexagon?",
    options: [540, 600, 720, 780],
    answer: 720,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 29,
    question:
      "If a box contains 5 red balls, 3 blue balls, and 2 green balls, what is the probability of randomly selecting a blue ball?",
    options: [1 / 5, 1 / 4, 1 / 3, 1 / 2],
    answer: 1 / 5,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 30,
    question: "Solve for y: 2y - 7 = 11",
    options: [3, 4, 5, 6],
    answer: 9,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 31,
    question:
      "If a right-angled triangle has legs of lengths 5 units and 12 units, what is the length of the hypotenuse?",
    options: [11, 13, 15, 17],
    answer: 13,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 32,
    question:
      "The perimeter of a square is 36 units. What is the length of one side of the square?",
    options: [6, 8, 9, 12],
    answer: 9,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 33,
    question:
      "If a number is increased by 20% and the result is 60, what is the original number?",
    options: [40, 45, 48, 50],
    answer: 50,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 34,
    question: "What is the volume of a cube with a side length of 3 units?",
    options: [9, 18, 27, 36],
    answer: 27,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 35,
    question:
      "If the base of a rectangle is 10 units and the height is 6 units, what is the area of the rectangle?",
    options: [40, 50, 60, 70],
    answer: 60,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 36,
    question: "Solve the equation: 3a - 8 = 13",
    options: [5, 7, 8, 9],
    answer: 7,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 37,
    question:
      "If a box contains 4 red balls, 5 green balls, and 6 blue balls, what is the ratio of red balls to the total number of balls?",
    options: ["4:15", "1:4", "2:5", "3:10"],
    answer: "4:15",
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 38,
    question:
      "The sum of three consecutive integers is 51. What are the integers?",
    options: [15, 16, 17, 18],
    answer: [16, 17, 18],
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 39,
    question:
      "If a cone has a radius of 4 units and a height of 6 units, what is the volume of the cone? (Use π = 3.14)",
    options: [50.24, 62.8, 75.36, 94.2],
    answer: 50.24,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 40,
    question: "What is the solution to the equation: 2x - 3 = 7",
    options: [2, 5, 6, 8],
    answer: 5,
    topic: "Maths",
    lvl: "medium",
  },
  {
    id: 41,
    question: "Find the value of sin(60 degrees) + cos(30 degrees)",
    options: [1, `√3/2`, `√2/2`, 1 / 2],
    answer: `√3/2`,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 42,
    question:
      "A car travels at a speed of 60 km/h for the first hour, 40 km/h for the second hour, and 30 km/h for the third hour. What is the average speed for the entire journey?",
    options: [40, 45, 50, 55],
    answer: 45,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 43,
    question:
      "The sum of the squares of two consecutive integers is 365. What are the integers?",
    options: [18, 19, 20, 21],
    answer: [18, 19],
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 44,
    question:
      "If a cylindrical tank has a radius of 5 meters and a height of 10 meters, what is the volume of the tank? (Use π = 3.14)",
    options: [392.5, 523.3, 785, 1570],
    answer: 785,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 45,
    question:
      "The nth term of an arithmetic sequence is given by the formula an = 3n + 5. What is the 10th term of the sequence?",
    options: [30, 35, 40, 45],
    answer: 35,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 46,
    question:
      "A triangle has side lengths of 8 cm, 15 cm, and 17 cm. Is it a right-angled triangle?",
    options: ["Yes", "No"],
    answer: "Yes",
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 47,
    question: "Solve the system of equations: 2x + y = 10, x - y = 2",
    options: [
      { x: 4, y: 6 },
      { x: 3, y: 5 },
      { x: 2, y: 8 },
      { x: 5, y: 4 },
    ],
    answer: { x: 4, y: 6 },
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 48,
    question:
      "The area of a circle is 154 square units. What is the radius of the circle? (Use π = 3.14)",
    options: [7, 7.5, 8, 8.5],
    answer: 7,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 49,
    question: "If log2(x) = 3, what is the value of x?",
    options: [2, 4, 6, 8],
    answer: 8,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 50,
    question:
      "A bag contains 5 red balls, 4 blue balls, and 3 green balls. If two balls are drawn at random without replacement, what is the probability that both are red?",
    options: [1 / 22, 2 / 33, 1 / 11, 5 / 36],
    answer: 1 / 22,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 51,
    question:
      "What is the sum of the infinite geometric series: 2 + 4 + 8 + ...?",
    options: [4, 8, 16, 5],
    answer: 4,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 52,
    question:
      "If a cone has a slant height of 10 units and a radius of 6 units, what is the lateral surface area of the cone? (Use π = 3.14)",
    options: [150, 180, 200, 240],
    answer: 180,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 53,
    question: "Solve the equation: log3(x) = 2",
    options: [3, 6, 9, 12],
    answer: 9,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 54,
    question:
      "A rectangle has a length three times its width. If the area is 72 square units, what are the dimensions of the rectangle?",
    options: [
      { length: 9, width: 3 },
      { length: 12, width: 4 },
      { length: 15, width: 5 },
      { length: 18, width: 6 },
    ],
    answer: { length: 12, width: 4 },
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 55,
    question:
      "The sum of the first 10 terms of an arithmetic series is 120. What is the common difference if the first term is 5?",
    options: [10, 12, 15, 18],
    answer: 3,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 56,
    question:
      "If a square has an area of 144 square units, what is the length of one side?",
    options: [8, 10, 12, 14],
    answer: 12,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 57,
    question:
      "The perimeter of a regular hexagon is 36 cm. What is the length of each side?",
    options: [4, 5, 6, 7],
    answer: 6,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 58,
    question:
      "If a box contains 2 red balls, 3 blue balls, and 4 green balls, how many different ways can you select one ball of each color?",
    options: [18, 20, 24, 30],
    answer: 24,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 59,
    question:
      "The perimeter of a rectangle is 24 units, and its length is 8 units. What is the width of the rectangle?",
    options: [4, 6, 8, 10],
    answer: 2,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 60,
    question: "Solve the equation: 2sin(x) - √3 = 0 for 0° ≤ x ≤ 360°",
    options: [30, 60, 90, 120],
    answer: 60,
    topic: "Maths",
    lvl: "hard",
  },
  {
    id: 61,
    question: "What is the chemical symbol for water?",
    options: ["W", "O", "H2O", "CO2"],
    answer: "H2O",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 62,
    question: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Venus", "Jupiter"],
    answer: "Mars",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 63,
    question: "What is the unit of measurement for force?",
    options: ["Watt", "Volt", "Newton", "Joule"],
    answer: "Newton",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 64,
    question: "Which gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    answer: "Carbon Dioxide",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 65,
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Mitochondria", "Ribosome", "Endoplasmic Reticulum"],
    answer: "Mitochondria",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 66,
    question: "Which gas is responsible for the greenhouse effect?",
    options: ["Oxygen", "Nitrogen", "Methane", "Helium"],
    answer: "Methane",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 67,
    question: "What is the chemical symbol for gold?",
    options: ["Au", "Ag", "Fe", "Cu"],
    answer: "Au",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 68,
    question: "Which force pulls objects towards the center of the Earth?",
    options: ["Friction", "Tension", "Gravity", "Magnetism"],
    answer: "Gravity",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 69,
    question: "What is the largest organ in the human body?",
    options: ["Heart", "Liver", "Brain", "Skin"],
    answer: "Skin",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 70,
    question: "Which gas do humans breathe in?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    answer: "Oxygen",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 71,
    question: "What is the chemical formula for table salt?",
    options: ["NaCl", "H2O", "CO2", "O2"],
    answer: "NaCl",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 72,
    question: "Which planet is closest to the Sun?",
    options: ["Mercury", "Venus", "Earth", "Mars"],
    answer: "Mercury",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 73,
    question:
      "What is the process by which plants make their own food using sunlight?",
    options: ["Respiration", "Photosynthesis", "Digestion", "Transpiration"],
    answer: "Photosynthesis",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 74,
    question: "What is the chemical symbol for oxygen?",
    options: ["O2", "O3", "O", "CO2"],
    answer: "O2",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 75,
    question: "Which scientist is known for the theory of relativity?",
    options: [
      "Isaac Newton",
      "Galileo Galilei",
      "Albert Einstein",
      "Stephen Hawking",
    ],
    answer: "Albert Einstein",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 76,
    question: "What is the main function of the kidneys in the human body?",
    options: ["Digestion", "Blood Circulation", "Filtration", "Respiration"],
    answer: "Filtration",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 77,
    question: "Which gas do plants release during photosynthesis?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"],
    answer: "Oxygen",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 78,
    question: "What is the chemical symbol for carbon?",
    options: ["C", "Ca", "Co", "Cu"],
    answer: "C",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 79,
    question: "What is the largest planet in our solar system?",
    options: ["Earth", "Jupiter", "Mars", "Venus"],
    answer: "Jupiter",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 80,
    question: "What is the hardest natural substance on Earth?",
    options: ["Gold", "Diamond", "Platinum", "Silver"],
    answer: "Diamond",
    topic: "Science",
    lvl: "easy",
  },
  {
    id: 81,
    question:
      "Which layer of the Earth's atmosphere protects life by blocking harmful solar radiation?",
    options: ["Stratosphere", "Mesosphere", "Thermosphere", "Ozone Layer"],
    answer: "Ozone Layer",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 82,
    question: "What is the chemical formula for the gas that makes soda fizzy?",
    options: ["CO2", "O2", "N2", "H2"],
    answer: "CO2",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 83,
    question:
      "Which element is essential for the formation of organic molecules in living organisms?",
    options: ["Carbon", "Iron", "Gold", "Copper"],
    answer: "Carbon",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 84,
    question:
      "What is the smallest unit of an element that retains its chemical properties?",
    options: ["Molecule", "Atom", "Cell", "Compound"],
    answer: "Atom",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 85,
    question: "Who is known as the father of modern physics?",
    options: [
      "Isaac Newton",
      "Galileo Galilei",
      "Albert Einstein",
      "Stephen Hawking",
    ],
    answer: "Albert Einstein",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 86,
    question:
      "What is the process by which plants lose water through small openings in their leaves?",
    options: ["Respiration", "Photosynthesis", "Transpiration", "Digestion"],
    answer: "Transpiration",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 87,
    question: "Which gas is responsible for the color of the Earth's sky?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"],
    answer: "Nitrogen",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 88,
    question:
      "What is the process by which plants make their own food using sunlight?",
    options: ["Respiration", "Photosynthesis", "Digestion", "Transpiration"],
    answer: "Photosynthesis",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 89,
    question: "Which scientist is credited with the discovery of penicillin?",
    options: [
      "Alexander Fleming",
      "Louis Pasteur",
      "Marie Curie",
      "Robert Koch",
    ],
    answer: "Alexander Fleming",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 90,
    question:
      "What is the process by which an organism develops from a fertilized egg to a mature individual?",
    options: ["Evolution", "Metamorphosis", "Reproduction", "Development"],
    answer: "Development",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 91,
    question: "Which metal is the best conductor of electricity?",
    options: ["Gold", "Silver", "Copper", "Aluminum"],
    answer: "Silver",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 92,
    question: "What is the chemical formula for common salt?",
    options: ["NaCl", "KCl", "CaCl2", "MgCl2"],
    answer: "NaCl",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 93,
    question: "Which gas do humans exhale during respiration?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    answer: "Carbon Dioxide",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 94,
    question:
      "What is the main function of the red blood cells in the human body?",
    options: [
      "Transport of Oxygen",
      "Protection against Infections",
      "Clotting of Blood",
      "Digestion",
    ],
    answer: "Transport of Oxygen",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 95,
    question: "Which gas do plants release during photosynthesis?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"],
    answer: "Oxygen",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 96,
    question: "What is the chemical symbol for the element iron?",
    options: ["Fe", "Au", "Ag", "Cu"],
    answer: "Fe",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 97,
    question: "What is the smallest bone in the human body?",
    options: ["Femur", "Stapes", "Radius", "Ulna"],
    answer: "Stapes",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 98,
    question: "Which gas is commonly known as laughing gas?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Nitrous Oxide"],
    answer: "Nitrous Oxide",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 99,
    question: "What is the chemical formula for methane?",
    options: ["CH4", "CO2", "H2O", "O2"],
    answer: "CH4",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 100,
    question: "What is the main component of natural gas?",
    options: ["Methane", "Ethane", "Propane", "Butane"],
    answer: "Methane",
    topic: "Science",
    lvl: "medium",
  },
  {
    id: 101,
    question:
      "In nuclear physics, what is the process by which the nucleus of an atom splits into two smaller nuclei?",
    options: ["Fusion", "Fission", "Radioactivity", "Decay"],
    answer: "Fission",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 102,
    question:
      "What is the name of the theory that explains the origin of the universe with a rapid expansion from a very high-density and high-temperature state?",
    options: [
      "Quantum Theory",
      "Big Bang Theory",
      "String Theory",
      "Relativity",
    ],
    answer: "Big Bang Theory",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 103,
    question:
      "Which subatomic particle is responsible for carrying a positive electric charge?",
    options: ["Proton", "Neutron", "Electron", "Quark"],
    answer: "Proton",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 104,
    question:
      "What is the phenomenon in which light is bent as it passes through a medium of different optical density?",
    options: ["Refraction", "Reflection", "Diffraction", "Interference"],
    answer: "Refraction",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 105,
    question: "Who formulated the laws of motion and universal gravitation?",
    options: [
      "Isaac Newton",
      "Galileo Galilei",
      "Albert Einstein",
      "Nikola Tesla",
    ],
    answer: "Isaac Newton",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 106,
    question: "What is the SI unit of electrical resistance?",
    options: ["Volt", "Ohm", "Ampere", "Watt"],
    answer: "Ohm",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 107,
    question:
      "Which particle is responsible for carrying a negative electric charge?",
    options: ["Proton", "Neutron", "Electron", "Positron"],
    answer: "Electron",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 108,
    question:
      "What is the process by which a substance changes directly from a gas to a solid without passing through the liquid phase?",
    options: ["Sublimation", "Condensation", "Evaporation", "Freezing"],
    answer: "Sublimation",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 109,
    question:
      "Which law of thermodynamics states that energy cannot be created or destroyed, only converted from one form to another?",
    options: ["Zeroth Law", "First Law", "Second Law", "Third Law"],
    answer: "First Law",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 110,
    question: "What is the speed of light in a vacuum?",
    options: ["300,000 km/s", "150,000 km/s", "600,000 km/s", "900,000 km/s"],
    answer: "300,000 km/s",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 111,
    question: "Who proposed the theory of relativity?",
    options: [
      "Isaac Newton",
      "Galileo Galilei",
      "Albert Einstein",
      "Stephen Hawking",
    ],
    answer: "Albert Einstein",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 112,
    question:
      "What is the process by which an unstable atomic nucleus loses energy by emitting radiation?",
    options: ["Fusion", "Fission", "Radioactivity", "Decay"],
    answer: "Radioactivity",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 113,
    question: "Which planet is known as the 'Red Planet'?",
    options: ["Mars", "Venus", "Jupiter", "Saturn"],
    answer: "Mars",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 114,
    question: "What is the study of the properties and behavior of light?",
    options: ["Optics", "Acoustics", "Thermodynamics", "Kinematics"],
    answer: "Optics",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 115,
    question: "What is the unit of electric charge?",
    options: ["Coulomb", "Ampere", "Volt", "Ohm"],
    answer: "Coulomb",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 116,
    question: "Which gas is known as 'laughing gas'?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Nitrous Oxide"],
    answer: "Nitrous Oxide",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 117,
    question: "What is the SI unit of power?",
    options: ["Watt", "Joule", "Newton", "Ampere"],
    answer: "Watt",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 118,
    question: "Which phenomenon is responsible for the formation of a rainbow?",
    options: ["Refraction", "Reflection", "Diffraction", "Interference"],
    answer: "Diffraction",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 119,
    question: "What is the term for the bending of waves around obstacles?",
    options: ["Refraction", "Reflection", "Diffraction", "Interference"],
    answer: "Diffraction",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 120,
    question: "Who discovered the electron?",
    options: ["J.J. Thomson", "Ernest Rutherford", "Niels Bohr", "Max Planck"],
    answer: "J.J. Thomson",
    topic: "Science",
    lvl: "hard",
  },
  {
    id: 121,
    question: "Who was the first President of the United States?",
    options: [
      "Thomas Jefferson",
      "George Washington",
      "John Adams",
      "Abraham Lincoln",
    ],
    answer: "George Washington",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 122,
    question:
      "In which year did Christopher Columbus first reach the Americas?",
    options: [1492, 1607, 1776, 1498],
    answer: 1492,
    topic: "History",
    lvl: "easy",
  },
  {
    id: 123,
    question: "Which ancient civilization built the pyramids in Egypt?",
    options: ["Greek", "Roman", "Egyptian", "Mesopotamian"],
    answer: "Egyptian",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 124,
    question: "What event marked the start of World War I?",
    options: [
      "Assassination of Archduke Franz Ferdinand",
      "Attack on Pearl Harbor",
      "Signing of the Treaty of Versailles",
      "Battle of Stalingrad",
    ],
    answer: "Assassination of Archduke Franz Ferdinand",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 125,
    question: "Who wrote the 'Communist Manifesto' along with Karl Marx?",
    options: [
      "Friedrich Engels",
      "Vladimir Lenin",
      "Joseph Stalin",
      "Leon Trotsky",
    ],
    answer: "Friedrich Engels",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 126,
    question:
      "Which famous speech begins with 'Four score and seven years ago'?",
    options: [
      "I Have a Dream",
      "Gettysburg Address",
      "Emancipation Proclamation",
      "Declaration of Independence",
    ],
    answer: "Gettysburg Address",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 127,
    question: "Who was the queen of ancient Egypt and the last pharaoh?",
    options: ["Cleopatra", "Nefertiti", "Hatshepsut", "Isis"],
    answer: "Cleopatra",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 128,
    question: "Which country was led by Adolf Hitler during World War II?",
    options: ["Italy", "Germany", "Japan", "Soviet Union"],
    answer: "Germany",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 129,
    question:
      "In which year did the United States declare its independence from Great Britain?",
    options: [1776, 1789, 1801, 1750],
    answer: 1776,
    topic: "History",
    lvl: "easy",
  },
  {
    id: 130,
    question:
      "Who was the first woman to win a Nobel Prize and the only person to win Nobel Prizes in two different scientific fields?",
    options: [
      "Marie Curie",
      "Rosalind Franklin",
      "Ada Lovelace",
      "Dorothy Crowfoot Hodgkin",
    ],
    answer: "Marie Curie",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 131,
    question:
      "What famous document begins with the words 'When in the course of human events'?",
    options: [
      "Magna Carta",
      "U.S. Constitution",
      "Declaration of Independence",
      "Bill of Rights",
    ],
    answer: "Declaration of Independence",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 132,
    question:
      "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
    options: [
      "Nikita Khrushchev",
      "Joseph Stalin",
      "Vladimir Putin",
      "Mikhail Gorbachev",
    ],
    answer: "Nikita Khrushchev",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 133,
    question:
      "What ancient wonder of the world was located in the city of Babylon?",
    options: [
      "Pyramids of Giza",
      "Hanging Gardens of Babylon",
      "Colossus of Rhodes",
      "Statue of Zeus at Olympia",
    ],
    answer: "Hanging Gardens of Babylon",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 134,
    question:
      "Who is known for leading the famous Salt March as a form of nonviolent protest against British salt monopoly?",
    options: [
      "Mahatma Gandhi",
      "Nelson Mandela",
      "Martin Luther King Jr.",
      "Winston Churchill",
    ],
    answer: "Mahatma Gandhi",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 135,
    question:
      "Which famous scientist formulated the laws of motion and gravity?",
    options: [
      "Isaac Newton",
      "Galileo Galilei",
      "Albert Einstein",
      "Nikola Tesla",
    ],
    answer: "Isaac Newton",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 136,
    question:
      "Who is often called the 'Father of Computer Science' and wrote the first computer program?",
    options: ["Bill Gates", "Alan Turing", "Charles Babbage", "Ada Lovelace"],
    answer: "Alan Turing",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 137,
    question:
      "Which city was the center of the Renaissance and home to artists like Leonardo da Vinci and Michelangelo?",
    options: ["Paris", "Venice", "Florence", "Rome"],
    answer: "Florence",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 138,
    question:
      "Who was the primary author of the 'Art of War,' an ancient Chinese military treatise?",
    options: ["Sun Tzu", "Confucius", "Laozi", "Mencius"],
    answer: "Sun Tzu",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 139,
    question: "In which century did the Renaissance period begin?",
    options: ["14th century", "15th century", "16th century", "17th century"],
    answer: "14th century",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 140,
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    options: [
      "Amelia Earhart",
      "Bessie Coleman",
      "Harriet Quimby",
      "Jacqueline Cochran",
    ],
    answer: "Amelia Earhart",
    topic: "History",
    lvl: "easy",
  },
  {
    id: 141,
    question:
      "What event is known as the 'Glorious Revolution' in English history?",
    options: [
      "Battle of Hastings",
      "Execution of Charles I",
      "Reign of Queen Victoria",
      "William of Orange's accession to the throne",
    ],
    answer: "William of Orange's accession to the throne",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 142,
    question:
      "Who was the leader of the Soviet Union during the Chernobyl nuclear disaster?",
    options: [
      "Mikhail Gorbachev",
      "Nikita Khrushchev",
      "Joseph Stalin",
      "Vladimir Putin",
    ],
    answer: "Mikhail Gorbachev",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 143,
    question: "During which war did the Battle of Gettysburg take place?",
    options: ["Civil War", "Revolutionary War", "World War I", "World War II"],
    answer: "Civil War",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 144,
    question: "Who was the founder of the Mongol Empire?",
    options: ["Genghis Khan", "Kublai Khan", "Attila the Hun", "Tamerlane"],
    answer: "Genghis Khan",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 145,
    question: "What famous event led to the start of the Renaissance in Italy?",
    options: [
      "Fall of Constantinople",
      "Black Death",
      "French Revolution",
      "Invention of the printing press",
    ],
    answer: "Fall of Constantinople",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 146,
    question:
      "Who was the first Emperor of China, known for the Terracotta Army?",
    options: ["Qin Shi Huang", "Han Wudi", "Emperor Wu", "Emperor Guangwu"],
    answer: "Qin Shi Huang",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 147,
    question:
      "Which ancient civilization developed the first known system of writing called cuneiform?",
    options: ["Sumerians", "Ancient Egyptians", "Greeks", "Romans"],
    answer: "Sumerians",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 148,
    question: "What is the significance of the Magna Carta in English history?",
    options: [
      "Establishment of constitutional monarchy",
      "Abolition of slavery",
      "Women's suffrage",
      "Religious Reformation",
    ],
    answer: "Establishment of constitutional monarchy",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 149,
    question:
      "Who was the famous nurse known for her work during the Crimean War?",
    options: [
      "Florence Nightingale",
      "Clara Barton",
      "Mary Seacole",
      "Dorothea Dix",
    ],
    answer: "Florence Nightingale",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 150,
    question:
      "What was the main cause of the Irish Potato Famine in the 19th century?",
    options: ["Drought", "Potato blight", "Invasion", "Economic collapse"],
    answer: "Potato blight",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 151,
    question: "Who was the legendary king of Camelot in Arthurian legend?",
    options: ["King Arthur", "Sir Lancelot", "Merlin", "Guinevere"],
    answer: "King Arthur",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 152,
    question:
      "What was the main goal of the Lewis and Clark expedition in the early 19th century?",
    options: [
      "Search for the Northwest Passage",
      "Exploration of the Louisiana Purchase",
      "Trade with Native American tribes",
      "Hunting for new species",
    ],
    answer: "Exploration of the Louisiana Purchase",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 153,
    question:
      "Which queen is known for her support of Christopher Columbus's voyage in 1492?",
    options: [
      "Queen Isabella I of Castile",
      "Queen Elizabeth I of England",
      "Catherine the Great",
      "Mary, Queen of Scots",
    ],
    answer: "Queen Isabella I of Castile",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 154,
    question:
      "Who was the primary author of the 'Wealth of Nations' and is considered the father of modern economics?",
    options: [
      "Adam Smith",
      "Karl Marx",
      "John Maynard Keynes",
      "Milton Friedman",
    ],
    answer: "Adam Smith",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 155,
    question:
      "What ancient civilization built the city of Machu Picchu in the Andes Mountains?",
    options: ["Maya", "Inca", "Aztec", "Olmec"],
    answer: "Inca",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 156,
    question: "Who was the founder of the Maurya Empire in ancient India?",
    options: ["Chandragupta Maurya", "Ashoka the Great", "Bindusara", "Porus"],
    answer: "Chandragupta Maurya",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 157,
    question:
      "Which famous battle marked the end of Napoleon's rule in France?",
    options: [
      "Battle of Leipzig",
      "Battle of Waterloo",
      "Battle of Austerlitz",
      "Battle of Jena-Auerstedt",
    ],
    answer: "Battle of Waterloo",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 158,
    question:
      "Who was the leader of the American Civil Rights Movement and gave the 'I Have a Dream' speech?",
    options: [
      "Malcolm X",
      "Martin Luther King Jr.",
      "Rosa Parks",
      "John Lewis",
    ],
    answer: "Martin Luther King Jr.",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 159,
    question:
      "Which famous explorer completed the first circumnavigation of the Earth?",
    options: [
      "Christopher Columbus",
      "Ferdinand Magellan",
      "James Cook",
      "John Cabot",
    ],
    answer: "Ferdinand Magellan",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 160,
    question:
      "Who was the leader of the Bolsheviks during the Russian Revolution?",
    options: ["Vladimir Lenin", "Joseph Stalin", "Leon Trotsky", "Nicholas II"],
    answer: "Vladimir Lenin",
    topic: "History",
    lvl: "medium",
  },
  {
    id: 161,
    question:
      "What was the main cause of the Peloponnesian War in ancient Greece?",
    options: [
      "Territorial disputes",
      "Trade routes",
      "Military alliances",
      "Athens' growing power",
    ],
    answer: "Territorial disputes",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 162,
    question:
      "Who was the Egyptian queen known for her relationships with Julius Caesar and Mark Antony?",
    options: ["Nefertiti", "Hatshepsut", "Cleopatra", "Tiye"],
    answer: "Cleopatra",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 163,
    question: "What was the significance of the Treaty of Westphalia in 1648?",
    options: [
      "End of the Thirty Years' War",
      "Establishment of the League of Nations",
      "Peace in the Middle East",
      "Formation of the European Union",
    ],
    answer: "End of the Thirty Years' War",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 164,
    question:
      "Who was the military leader responsible for the unification of Germany in the 19th century?",
    options: [
      "Otto von Bismarck",
      "Kaiser Wilhelm I",
      "Frederick II",
      "Franz Joseph I",
    ],
    answer: "Otto von Bismarck",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 165,
    question:
      "What was the main cause of the Opium Wars between China and Britain in the 19th century?",
    options: [
      "Religious conflicts",
      "Trade imbalance",
      "Colonial expansion",
      "Drug trade",
    ],
    answer: "Drug trade",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 166,
    question: "Who was the Aztec ruler at the time of the Spanish conquest?",
    options: ["Montezuma II", "Cuauhtémoc", "Ahuitzotl", "Moctezuma I"],
    answer: "Montezuma II",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 167,
    question: "What was the primary cause of the French Revolution?",
    options: [
      "Economic inequality",
      "Foreign invasion",
      "Religious conflicts",
      "Monarchical tyranny",
    ],
    answer: "Economic inequality",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 168,
    question:
      "Who was the influential philosopher behind the concept of existentialism?",
    options: [
      "Jean-Jacques Rousseau",
      "Søren Kierkegaard",
      "Friedrich Nietzsche",
      "Albert Camus",
    ],
    answer: "Søren Kierkegaard",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 169,
    question:
      "What was the impact of the Taiping Rebellion in 19th-century China?",
    options: [
      "Establishment of a democratic government",
      "Collapse of the Qing Dynasty",
      "Spread of Buddhism",
      "Formation of the Chinese Communist Party",
    ],
    answer: "Collapse of the Qing Dynasty",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 170,
    question:
      "Who was the architect of the unification of Italy in the 19th century?",
    options: [
      "Giuseppe Garibaldi",
      "Camillo Cavour",
      "Giuseppe Mazzini",
      "Victor Emmanuel II",
    ],
    answer: "Camillo Cavour",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 171,
    question: "What was the outcome of the Boxer Rebellion in China?",
    options: [
      "Victory of the Boxers",
      "End of foreign influence",
      "Collapse of the Qing Dynasty",
      "Establishment of a constitutional monarchy",
    ],
    answer: "Collapse of the Qing Dynasty",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 172,
    question:
      "Who was the Russian mystic and advisor to the Romanov family, Rasputin?",
    options: [
      "Grigori Rasputin",
      "Leon Trotsky",
      "Vladimir Lenin",
      "Joseph Stalin",
    ],
    answer: "Grigori Rasputin",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 173,
    question: "What was the impact of the Cultural Revolution in China?",
    options: [
      "Industrial growth",
      "Cultural preservation",
      "Political repression",
      "Technological innovation",
    ],
    answer: "Political repression",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 174,
    question:
      "Who was the leader of the Haitian Revolution, leading to the establishment of Haiti as an independent nation?",
    options: [
      "Toussaint Louverture",
      "Jean-Jacques Dessalines",
      "Henri Christophe",
      "Alexandre Pétion",
    ],
    answer: "Toussaint Louverture",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 175,
    question: "What was the significance of the Balfour Declaration in 1917?",
    options: [
      "Establishment of the League of Nations",
      "Recognition of Israel",
      "Declaration of war on Germany",
      "Support for a Jewish homeland in Palestine",
    ],
    answer: "Support for a Jewish homeland in Palestine",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 176,
    question:
      "Who was the first President of the United States to be impeached?",
    options: [
      "Andrew Johnson",
      "Richard Nixon",
      "Bill Clinton",
      "Donald Trump",
    ],
    answer: "Andrew Johnson",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 177,
    question:
      "What was the significance of the Treaty of Versailles after World War I?",
    options: [
      "Promotion of peace and stability",
      "Punishment of Germany",
      "Formation of the United Nations",
      "Creation of NATO",
    ],
    answer: "Punishment of Germany",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 178,
    question:
      "Who was the leader of the Mexican revolution in the early 20th century?",
    options: [
      "Emiliano Zapata",
      "Pancho Villa",
      "Porfirio Díaz",
      "Venustiano Carranza",
    ],
    answer: "Emiliano Zapata",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 179,
    question:
      "What was the main cause of the Irish War of Independence in the early 20th century?",
    options: [
      "Religious conflict",
      "Territorial disputes",
      "Opposition to British rule",
      "Economic inequality",
    ],
    answer: "Opposition to British rule",
    topic: "History",
    lvl: "hard",
  },
  {
    id: 180,
    question:
      "Who was the British Prime Minister during the Falklands War in 1982?",
    options: [
      "Margaret Thatcher",
      "Winston Churchill",
      "Tony Blair",
      "John Major",
    ],
    answer: "Margaret Thatcher",
    topic: "History",
    lvl: "hard",
  },
];
